apiVersion: apps/v1
kind: Deployment
metadata:
  name: container2-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: container2
  template:
    metadata:
      labels:
        app: container2
    spec:
      containers:
      - name: container2
        image: us-central1-docker.pkg.dev/assignment3-428215/k8srepository/container2:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 7000
        volumeMounts:
          - name: data-volume
            mountPath: /harshil_PV_dir
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: host-pvc

